# Generated by Django 3.1.5 on 2021-01-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=6)),
                ('nama', models.CharField(max_length=50)),
                ('harga', models.IntegerField(default=0)),
                ('kategori', models.CharField(max_length=10)),
            ],
        ),
    ]
