# Generated by Django 3.1.5 on 2021-01-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Kategori_Modul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_modul', models.IntegerField(default=0)),
                ('id_kategori', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='modul',
            name='kode',
        ),
        migrations.AlterField(
            model_name='modul',
            name='kategori',
            field=models.IntegerField(default=0),
        ),
    ]
