# Generated by Django 3.1.5 on 2021-01-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20210121_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='modul',
            name='banner_img',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
