# Generated by Django 3.1.5 on 2021-01-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20210121_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modul',
            name='nama',
            field=models.CharField(max_length=100),
        ),
    ]
