# Generated by Django 3.1.5 on 2021-01-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20210121_1501'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kategori_Modul',
        ),
        migrations.RemoveField(
            model_name='modul',
            name='kategori',
        ),
        migrations.AddField(
            model_name='modul',
            name='kategori',
            field=models.ManyToManyField(to='homepage.Kategori'),
        ),
    ]
