# Generated by Django 3.1.5 on 2021-01-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_modul_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modul',
            name='uri',
            field=models.CharField(max_length=50),
        ),
    ]
