# Generated by Django 3.1.5 on 2021-01-21 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_auto_20210121_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modul',
            name='uri',
        ),
    ]
